name: Baseline Integrity

on: [push, pull_request]

jobs:
  check-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Reject mock/demo/empty parquet
        run: |
          set -e
          if ls baselines/2s/ticks/*/*mock*.parquet 2>/dev/null; then exit 1; fi
          if ls baselines/2s/ticks/*/*_demo*.parquet 2>/dev/null; then exit 1; fi
          python - <<PY
import pathlib, sys
root = pathlib.Path("baselines/2s/ticks")
bad = []
for f in root.rglob("*.parquet"):
    if f.stat().st_size == 0: bad.append(str(f))
if bad:
    print("Empty parquet:", bad); sys.exit(1)
PY
