name: Court 1s Integrity

on: [push, pull_request]

jobs:
  check-court-1s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Reject mock/demo/empty parquet
        run: |
          set -e
          if ls court/1s/ticks/*/*mock*.parquet 2>/dev/null; then exit 1; fi
          if ls court/1s/ticks/*/*_demo*.parquet 2>/dev/null; then exit 1; fi
        shell: bash
      - name: Check for empty parquet files
        run: |
          python - <<PY
          import pathlib, sys
          root = pathlib.Path("court/1s/ticks")
          bad = []
          for f in root.rglob("*.parquet"):
              if f.stat().st_size == 0: bad.append(str(f))
          if bad:
              print("Empty parquet:", bad); sys.exit(1)
          PY
        shell: bash
      - name: Check for ABORT tags in analysis results
        run: |
          set -e
          if grep -r "\[ABORT:" court/1s/evidence/ 2>/dev/null; then
            echo "[CI:fail:abort_tags] Found ABORT tags in court evidence"
            exit 2
          fi
        shell: bash
      - name: Check InfoShare results
        run: |
          python - <<PY
          import json, sys
          try:
              with open("court/1s/evidence/info_share_results.json") as f:
                  data = json.load(f)
              if not data.get("bounds") or data["bounds"] == {}:
                  print("[CI:fail:infoshare_empty] InfoShare bounds are empty")
                  sys.exit(2)
          except FileNotFoundError:
              print("[CI:fail:infoshare_missing] InfoShare results not found")
              sys.exit(2)
          PY
        shell: bash
      - name: Check Spread results
        run: |
          python - <<PY
          import json, sys
          try:
              with open("court/1s/evidence/spread_results.json") as f:
                  data = json.load(f)
              if data.get("permutes", 0) < 1000:
                  print("[CI:fail:permutes_low] Spread permutations < 1000")
                  sys.exit(2)
          except FileNotFoundError:
              print("[CI:fail:spread_missing] Spread results not found")
              sys.exit(2)
          PY
        shell: bash
      - name: Debug Lead-Lag results
        run: |
          set -e
          f=$(git ls-files | grep -E 'leadlag_results\.json$' || true)
          [ -z "$f" ] && echo "[CI:debug] no leadlag_results.json found" && exit 2
          echo "[CI:debug] file=$f"
          python - <<'PY'
import json,sys,glob
fns = glob.glob("**/leadlag_results.json", recursive=True)
if not fns:
    print("[CI:debug] no file"); sys.exit(2)
p=fns[0]
d=json.load(open(p))
print("[CI:debug] keys=", list(d.keys()))
print("[CI:debug] venues_count=", d.get("venues_count"))
edges=d.get("edges", [])
print("[CI:debug] edges_count=", len(edges))
print("[CI:debug] horizons=", d.get("horizons"))
PY
        shell: bash
      - name: Check Lead-Lag results
        run: |
          python - <<PY
          import json, sys
          try:
              with open("court/1s/evidence/leadlag_results.json") as f:
                  data = json.load(f)
              if not data.get("edges") or data["edges"] == []:
                  print("[CI:fail:leadlag_empty] Lead-Lag edges are empty")
                  sys.exit(2)
          except FileNotFoundError:
              print("[CI:fail:leadlag_missing] Lead-Lag results not found")
              sys.exit(2)
          PY
        shell: bash