name: release
on:
  push:
    tags:
      - 'v*'
      - 'research-*'
      - 'court-*'
permissions:
  contents: write
  actions: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Create release directory
        run: mkdir -p out
      - name: Collect artifacts
        run: |
          tar -czf out/exports.tgz exports || true
          tar -czf out/baselines_2s_evidence.tgz baselines/2s/evidence || true
          tar -czf out/court_1s.tgz court/1s || true
          tar -czf out/reports.tgz $(git ls-files '*REPORT*.md' '*SUMMARY*.md' '*DECISION*.md' || true) || true
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
